Support config.js, introduce context type for global state, and export config types
dethcrypto/eth-sdk pull request #33
Opened 2021-10-29 12:51 UTC by hasparus

## What's changed?

### (breaking) `--out` flag in CLI is no longer supported in favor of `config.outputPath`

We print an error message promising migration notes in [/releases](https://github.com/dethcrypto/eth-sdk/releases) so I have to write a changeset for it.

![image](https://user-images.githubusercontent.com/15332326/139580128-e0ca5458-3f3b-49a7-b31b-caaf505056c5.png)

### configuration can now be written in JavaScript and check with `@ts-check`

Supporting `.ts` can be implemented in a separate PR.

![image](https://user-images.githubusercontent.com/15332326/139579600-a883456a-a57e-4681-94ac-987ae2429321.png)
 
 
 ### Introduced EthSdkCtx
 
 Big functions that know about everything anyway can stop accepting 5 args.
 
 ```ts
interface EthSdkCtx {
  readonly cliArgs: EthSdkCliArgs
  readonly config: EthSdkConfig
  readonly fs: Fs
}
```

### Updated TypeScript to v4.4 and turned on `exactOptionalPropertyTypes`

It's still a small codebase so there's no cost here, but it might catch few bugs in the future.

### Added _.vscode/tasks.json_ and _.vscode/settings.json_

- _settings.json_ states that we want to use TypeScript version from _node_modules_
- _tasks.json_ adds tasks to populate VSCode _"Problems"_ tab with ESLint and TypeScript errors. `"typecheck"` tasks is using `"type": "shell"` instead of `"type": "npm"` to make error paths start from root dir.

2021-10-31 20:04 UTC, krzkaczor approved these changes
Good job! 

I would suggest removing backward compatibility if this requires any additional work (like support for contracts.json). More code = more maintenance. We don't need to support any level of backward compatibility because the project is not that popular right now 😉

2021-10-31 20:04 UTC, krzkaczor commented on packages/eth-sdk/src/config/findConfigFile.ts
> +const CONFIG_FILENAMES = ['contracts.json', 'contracts.js', 'config.js', 'config.json']
remove support for `contracts.json`

2021-10-31 20:04 UTC, krzkaczor commented on packages/eth-sdk/src/config/traverse.ts
> +export async function traverseSdkDefinition(
rename -- we don't use SdkDefinition name anymore.

2021-10-31 20:05 UTC, krzkaczor requested changes
misclick

2021-11-01 10:03 UTC, hasparus commented on packages/eth-sdk/src/config/readConfig.ts
> +      if (fileName === 'contracts') {
fwiw: we have a warning already

```
Error: Couldn't find a config file. Create one of config.js, config.json, eth-sdk.config.js, eth-sdk.config.json in /home/runner/work/eth-sdk/eth-sdk/examples/vite-react/eth-sdk
```

2021-11-01 10:26 UTC, krzkaczor commented on packages/eth-sdk/src/config/readConfig.test.ts
> +function mockRequire(filePath: string, result: unknown) {
It's fine 👍

2021-11-01 11:25 UTC, hasparus commented
Note; I've also exported `defineConfig` and started supporting `.cjs` extension.

2021-11-01 18:30 UTC, krzkaczor approved these changes
Great work!

2021-11-01 18:48 UTC, krzkaczor reviewed
One last thing: can you update readme getting started guide (`contracts.json` -> `config.json` etc.)

2021-11-02 07:52 UTC, hasparus commented
> One last thing: can you update readme getting started guide (contracts.json -> config.json etc.)

We'll need to release fast, because everybody visiting the repo will see new readme.

2021-11-02 08:08 UTC, merged