follow proxies
dethcrypto/eth-sdk pull request #41
Opened 2021-11-09 23:09 UTC by hasparus

### What's changed?

We now detect proxies when fetching ABI and fetch implementation ABI instead.

### What's left do to here?

- [ ] Needs rebase on top of master
- [ ] Unit tests
- [ ] Rename config.infura to config.rpcProvider
- [ ] If we want to support Infura Secrets we should use project ID instead of endpoint. I'd probably get rid of all mentions of infura for now.

2021-11-11 20:31 UTC, krzkaczor approved these changes
Nice tests!

2021-11-12 09:23 UTC, krzkaczor requested changes
This needs readme updates:
* note about new `rpcProvider` option
* note about this feature

2021-11-12 12:24 UTC, hasparus commented on packages/eth-sdk/README.md
> +  - [Videos](#videos)
There is a Markdown All in One extension for VSCode which updates the TOC automatically.

2021-11-12 14:33 UTC, krzkaczor approved these changes

2021-11-12 15:04 UTC, merged